artifacts_root: artifacts 

data_ingestion:
 root_dir: artifacts/data_ingestion
 source_url: https://github.com/mayurkadam9833/Datasets/raw/refs/heads/main/insurance.zip
 local_data_file: artifacts/data_ingestion/insurance.zip
 unzip_dir: artifacts/data_ingestion

data_validation:
 root_dir: artifacts/data_validation
 unzip_data_path: artifacts/data_ingestion/insurance.csv
 STATUS_FILE: artifacts/data_validation/validation_status.txt

data_transformation:
 root_dir: artifacts/data_transformation
 data_path: artifacts/data_ingestion/insurance.csv

model_trainer:
 root_dir: artifacts/model_trainer
 train_data_path: artifacts/data_transformation/train.csv
 test_data_path: artifacts/data_transformation/test.csv
 model_name: model.joblib

model_evalution:
 root_dir: artifacts/model_evalution
 test_data_path: artifacts/data_transformation/train.csv 
 model_path: artifacts/model_trainer/model.joblib 
 metric_file: artifacts/model_evalution/metric.json
